# Generated by Django 2.1.3 on 2018-12-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mineral_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mineral',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='mineral',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
